// i18n System — 24 lingue supportate
const { getDb } = require("./db");

const SUPPORTED_LANGUAGES = ["en","it","fr","es","de","pt","nl","ru","zh","ja","ko","ar","hi","tr","pl","sv","da","no","fi","el","he","th","vi","sw"];
const DEFAULT_LANG = "en";

// Compact translations structure: [key][lang] = value
// Using object for each key to keep it readable
const T = {
  // Navigation
  nav_home:               {en:"Home",it:"Home",fr:"Accueil",es:"Inicio",de:"Startseite",pt:"Início",nl:"Home",ru:"Главная",zh:"首页",ja:"ホーム",ko:"홈",ar:"الرئيسية",hi:"होम",tr:"Ana Sayfa",pl:"Strona główna",sv:"Hem",da:"Hjem",no:"Hjem",fi:"Koti",el:"Αρχική",he:"דף הבית",th:"หน้าแรก",vi:"Trang chủ",sw:"Nyumbani"},
  nav_library:            {en:"Library",it:"Biblioteca",fr:"Bibliothèque",es:"Biblioteca",de:"Bibliothek",pt:"Biblioteca",nl:"Bibliotheek",ru:"Библиотека",zh:"图书馆",ja:"図書館",ko:"도서관",ar:"المكتبة",hi:"पुस्तकालय",tr:"Kütüphane",pl:"Biblioteka",sv:"Bibliotek",da:"Bibliotek",no:"Bibliotek",fi:"Kirjasto",el:"Βιβλιοθήκη",he:"ספרייה",th:"ห้องสมุด",vi:"Thư viện",sw:"Maktaba"},
  nav_login:              {en:"Login",it:"Accedi",fr:"Connexion",es:"Iniciar sesión",de:"Anmelden",pt:"Entrar",nl:"Inloggen",ru:"Войти",zh:"登录",ja:"ログイン",ko:"로그인",ar:"تسجيل الدخول",hi:"लॉग इन",tr:"Giriş Yap",pl:"Zaloguj się",sv:"Logga in",da:"Log ind",no:"Logg inn",fi:"Kirjaudu",el:"Σύνδεση",he:"התחברות",th:"เข้าสู่ระบบ",vi:"Đăng nhập",sw:"Ingia"},
  nav_register:           {en:"Register",it:"Registrati",fr:"S'inscrire",es:"Registrarse",de:"Registrieren",pt:"Registrar",nl:"Registreren",ru:"Регистрация",zh:"注册",ja:"登録",ko:"회원가입",ar:"التسجيل",hi:"पंजीकरण",tr:"Kayıt Ol",pl:"Rejestracja",sv:"Registrera",da:"Registrer",no:"Registrer",fi:"Rekisteröidy",el:"Εγγραφή",he:"הרשמה",th:"สมัครสมาชิก",vi:"Đăng ký",sw:"Jisajili"},
  nav_logout:             {en:"Logout",it:"Esci",fr:"Déconnexion",es:"Cerrar sesión",de:"Abmelden",pt:"Sair",nl:"Uitloggen",ru:"Выйти",zh:"退出",ja:"ログアウト",ko:"로그아웃",ar:"تسجيل الخروج",hi:"लॉग आउट",tr:"Çıkış Yap",pl:"Wyloguj się",sv:"Logga ut",da:"Log ud",no:"Logg ut",fi:"Kirjaudu ulos",el:"Αποσύνδεση",he:"התנתקות",th:"ออกจากระบบ",vi:"Đăng xuất",sw:"Toka"},
  nav_admin:              {en:"Admin Panel",it:"Pannello Admin",fr:"Panneau Admin",es:"Panel Admin",de:"Admin-Bereich",pt:"Painel Admin",nl:"Adminpaneel",ru:"Панель администратора",zh:"管理面板",ja:"管理パネル",ko:"관리자 패널",ar:"لوحة الإدارة",hi:"व्यवस्थापक पैनल",tr:"Yönetici Paneli",pl:"Panel administracyjny",sv:"Adminpanel",da:"Adminpanel",no:"Adminpanel",fi:"Ylläpitopaneeli",el:"Πίνακας διαχείρισης",he:"לוח ניהול",th:"แผงผู้ดูแล",vi:"Bảng quản trị",sw:"Jopo la Usimamizi"},
  nav_profile:            {en:"Profile",it:"Profilo",fr:"Profil",es:"Perfil",de:"Profil",pt:"Perfil",nl:"Profiel",ru:"Профиль",zh:"个人资料",ja:"プロフィール",ko:"프로필",ar:"الملف الشخصي",hi:"प्रोफ़ाइल",tr:"Profil",pl:"Profil",sv:"Profil",da:"Profil",no:"Profil",fi:"Profiili",el:"Προφίλ",he:"פרופיל",th:"โปรไฟล์",vi:"Hồ sơ",sw:"Wasifu"},

  // Library
  library_title:          {en:"📚 My Bookshelf",it:"📚 La Mia Libreria",fr:"📚 Ma Bibliothèque",es:"📚 Mi Biblioteca",de:"📚 Mein Bücherregal",pt:"📚 Minha Estante",nl:"📚 Mijn Boekenplank",ru:"📚 Моя книжная полка",zh:"📚 我的书架",ja:"📚 私の本棚",ko:"📚 내 책장",ar:"📚 مكتبتي",hi:"📚 मेरी किताबों की अलमारी",tr:"📚 Kitaplığım",pl:"📚 Moja biblioteczka",sv:"📚 Min Bokhylla",da:"📚 Min Bogreol",no:"📚 Min Bokhylle",fi:"📚 Kirjahyllyni",el:"📚 Η Βιβλιοθήκη μου",he:"📚 ספרייתי",th:"📚 ชั้นหนังสือของฉัน",vi:"📚 Tủ sách của tôi",sw:"📚 Rafu Yangu ya Vitabu"},
  library_subtitle:       {en:"Your personal digital library — read, learn, grow",it:"La tua biblioteca digitale — leggi, impara, cresci",fr:"Votre bibliothèque numérique — lisez, apprenez, grandissez",es:"Tu biblioteca digital — lee, aprende, crece",de:"Deine digitale Bibliothek — lesen, lernen, wachsen",pt:"Sua biblioteca digital — leia, aprenda, cresça",nl:"Uw digitale bibliotheek — lees, leer, groei",ru:"Ваша цифровая библиотека — читайте, учитесь, растите",zh:"您的个人数字图书馆 — 阅读、学习、成长",ja:"あなたのデジタル図書館 — 読み、学び、成長する",ko:"디지털 도서관 — 읽고, 배우고, 성장하세요",ar:"مكتبتك الرقمية — اقرأ، تعلم، انمو",hi:"आपकी डिजिटल लाइब्रेरी — पढ़ें, सीखें, बढ़ें",tr:"Dijital kütüphaneniz — okuyun, öğrenin, büyüyün",pl:"Twoja cyfrowa biblioteka — czytaj, ucz się, rozwijaj",sv:"Ditt digitala bibliotek — läs, lär, väx",da:"Dit digitale bibliotek — læs, lær, voks",no:"Ditt digitale bibliotek — les, lær, voks",fi:"Digitaalinen kirjastosi — lue, opi, kasva",el:"Η ψηφιακή βιβλιοθήκη σας — διαβάστε, μάθετε, αναπτυχθείτε",he:"הספרייה הדיגיטלית שלך — קרא, למד, גדל",th:"ห้องสมุดดิจิทัลของคุณ — อ่าน เรียนรู้ เติบโต",vi:"Thư viện kỹ thuật số của bạn — đọc, học, phát triển",sw:"Maktaba yako ya kidijitali — soma, jifunze, kua"},
  library_search:         {en:"Search by title, author, or description...",it:"Cerca per titolo, autore o descrizione...",fr:"Rechercher par titre, auteur ou description...",es:"Buscar por título, autor o descripción...",de:"Suche nach Titel, Autor oder Beschreibung...",pt:"Pesquisar por título, autor ou descrição...",nl:"Zoeken op titel, auteur of beschrijving...",ru:"Поиск по названию, автору или описанию...",zh:"按标题、作者或描述搜索...",ja:"タイトル、著者、説明で検索...",ko:"제목, 저자 또는 설명으로 검색...",ar:"البحث حسب العنوان أو المؤلف أو الوصف...",hi:"शीर्षक, लेखक या विवरण द्वारा खोजें...",tr:"Başlık, yazar veya açıklamaya göre ara...",pl:"Szukaj po tytule, autorze lub opisie...",sv:"Sök efter titel, författare eller beskrivning...",da:"Søg efter titel, forfatter eller beskrivelse...",no:"Søk etter tittel, forfatter eller beskrivelse...",fi:"Hae otsikolla, tekijällä tai kuvauksella...",el:"Αναζήτηση με τίτλο, συγγραφέα ή περιγραφή...",he:"חיפוש לפי כותרת, מחבר או תיאור...",th:"ค้นหาตามชื่อเรื่อง ผู้แต่ง หรือคำอธิบาย...",vi:"Tìm kiếm theo tiêu đề, tác giả hoặc mô tả...",sw:"Tafuta kwa kichwa, mwandishi, au maelezo..."},
  library_empty:          {en:"Your bookshelf is empty — add your first book!",it:"La tua libreria è vuota — aggiungi il tuo primo libro!",fr:"Votre bibliothèque est vide — ajoutez votre premier livre!",es:"Tu biblioteca está vacía — ¡añade tu primer libro!",de:"Dein Bücherregal ist leer — füge dein erstes Buch hinzu!",pt:"Sua estante está vazia — adicione seu primeiro livro!",nl:"Je boekenplank is leeg — voeg je eerste boek toe!",ru:"Ваша полка пуста — добавьте первую книгу!",zh:"您的书架是空的 — 添加您的第一本书！",ja:"本棚は空です — 最初の本を追加しましょう！",ko:"책장이 비어 있습니다 — 첫 번째 책을 추가하세요!",ar:"مكتبتك فارغة — أضف كتابك الأول!",hi:"आपकी किताबों की अलमारी खाली है — अपनी पहली किताब जोड़ें!",tr:"Kitaplığınız boş — ilk kitabınızı ekleyin!",pl:"Twoja biblioteczka jest pusta — dodaj pierwszą książkę!",sv:"Din bokhylla är tom — lägg till din första bok!",da:"Din bogreol er tom — tilføj din første bog!",no:"Bokhyllen din er tom — legg til din første bok!",fi:"Kirjahyllysi on tyhjä — lisää ensimmäinen kirjasi!",el:"Η βιβλιοθήκη σας είναι άδεια — προσθέστε το πρώτο σας βιβλίο!",he:"ספריית הספרים שלך ריקה — הוסף את הספר הראשון שלך!",th:"ชั้นหนังสือของคุณว่างเปล่า — เพิ่มหนังสือเล่มแรกของคุณ!",vi:"Tủ sách của bạn trống — thêm cuốn sách đầu tiên!",sw:"Rafu yako iko tupu — ongeza kitabu chako cha kwanza!"},
  library_books:          {en:"{count} books",it:"{count} libri",fr:"{count} livres",es:"{count} libros",de:"{count} Bücher",pt:"{count} livros",nl:"{count} boeken",ru:"{count} книг",zh:"{count} 本书",ja:"{count} 冊",ko:"{count}권",ar:"{count} كتب",hi:"{count} किताबें",tr:"{count} kitap",pl:"{count} książek",sv:"{count} böcker",da:"{count} bøger",no:"{count} bøker",fi:"{count} kirjaa",el:"{count} βιβλία",he:"{count} ספרים",th:"{count} เล่ม",vi:"{count} cuốn sách",sw:"{count} vitabu"},
  library_book:           {en:"{count} book",it:"{count} libro",fr:"{count} livre",es:"{count} libro",de:"{count} Buch",pt:"{count} livro",nl:"{count} boek",ru:"{count} книга",zh:"{count} 本书",ja:"{count} 冊",ko:"{count}권",ar:"{count} كتاب",hi:"{count} किताब",tr:"{count} kitap",pl:"{count} książka",sv:"{count} bok",da:"{count} bog",no:"{count} bok",fi:"{count} kirja",el:"{count} βιβλίο",he:"{count} ספר",th:"{count} เล่ม",vi:"{count} cuốn sách",sw:"{count} kitabu"},

  // Filters
  filter_all:             {en:"All",it:"Tutti",fr:"Tous",es:"Todos",de:"Alle",pt:"Todos",nl:"Alle",ru:"Все",zh:"全部",ja:"すべて",ko:"전체",ar:"الكل",hi:"सभी",tr:"Tümü",pl:"Wszystkie",sv:"Alla",da:"Alle",no:"Alle",fi:"Kaikki",el:"Όλα",he:"הכל",th:"ทั้งหมด",vi:"Tất cả",sw:"Zote"},
  filter_category:        {en:"Category",it:"Categoria",fr:"Catégorie",es:"Categoría",de:"Kategorie",pt:"Categoria",nl:"Categorie",ru:"Категория",zh:"分类",ja:"カテゴリー",ko:"카테고리",ar:"الفئة",hi:"श्रेणी",tr:"Kategori",pl:"Kategoria",sv:"Kategori",da:"Kategori",no:"Kategori",fi:"Luokka",el:"Κατηγορία",he:"קטגוריה",th:"หมวดหมู่",vi:"Danh mục",sw:"Kategoria"},
  filter_language:        {en:"Language",it:"Lingua",fr:"Langue",es:"Idioma",de:"Sprache",pt:"Idioma",nl:"Taal",ru:"Язык",zh:"语言",ja:"言語",ko:"언어",ar:"اللغة",hi:"भाषा",tr:"Dil",pl:"Język",sv:"Språk",da:"Sprog",no:"Språk",fi:"Kieli",el:"Γλώσσα",he:"שפה",th:"ภาษา",vi:"Ngôn ngữ",sw:"Lugha"},
  filter_year:            {en:"Year",it:"Anno",fr:"Année",es:"Año",de:"Jahr",pt:"Ano",nl:"Jaar",ru:"Год",zh:"年份",ja:"年",ko:"년도",ar:"السنة",hi:"वर्ष",tr:"Yıl",pl:"Rok",sv:"År",da:"År",no:"År",fi:"Vuosi",el:"Έτος",he:"שנה",th:"ปี",vi:"Năm",sw:"Mwaka"},
  filter_recommended:     {en:"⭐ Recommended",it:"⭐ Raccomandati",fr:"⭐ Recommandés",es:"⭐ Recomendados",de:"⭐ Empfohlen",pt:"⭐ Recomendados",nl:"⭐ Aanbevolen",ru:"⭐ Рекомендуемые",zh:"⭐ 推荐",ja:"⭐ おすすめ",ko:"⭐ 추천",ar:"⭐ موصى به",hi:"⭐ अनुशंसित",tr:"⭐ Önerilenler",pl:"⭐ Polecane",sv:"⭐ Rekommenderade",da:"⭐ Anbefalede",no:"⭐ Anbefalte",fi:"⭐ Suositellut",el:"⭐ Προτεινόμενα",he:"⭐ מומלץ",th:"⭐ แนะนำ",vi:"⭐ Đề xuất",sw:"⭐ Ilipendekezwa"},
  filter_sort:            {en:"Sort by",it:"Ordina per",fr:"Trier par",es:"Ordenar por",de:"Sortieren nach",pt:"Ordenar por",nl:"Sorteren op",ru:"Сортировать",zh:"排序",ja:"並び替え",ko:"정렬",ar:"ترتيب حسب",hi:"क्रमबद्ध करें",tr:"Sırala",pl:"Sortuj",sv:"Sortera",da:"Sorter",no:"Sorter",fi:"Lajittele",el:"Ταξινόμηση",he:"מיין",th:"เรียงตาม",vi:"Sắp xếp",sw:"Panga"},
  sort_title:             {en:"Title",it:"Titolo",fr:"Titre",es:"Título",de:"Titel",pt:"Título",nl:"Titel",ru:"Название",zh:"标题",ja:"タイトル",ko:"제목",ar:"العنوان",hi:"शीर्षक",tr:"Başlık",pl:"Tytuł",sv:"Titel",da:"Titel",no:"Tittel",fi:"Otsikko",el:"Τίτλος",he:"כותרת",th:"ชื่อเรื่อง",vi:"Tiêu đề",sw:"Kichwa"},
  sort_author:            {en:"Author",it:"Autore",fr:"Auteur",es:"Autor",de:"Autor",pt:"Autor",nl:"Auteur",ru:"Автор",zh:"作者",ja:"著者",ko:"저자",ar:"المؤلف",hi:"लेखक",tr:"Yazar",pl:"Autor",sv:"Författare",da:"Forfatter",no:"Forfatter",fi:"Tekijä",el:"Συγγραφέας",he:"מחבר",th:"ผู้แต่ง",vi:"Tác giả",sw:"Mwandishi"},
  sort_year:              {en:"Year",it:"Anno",fr:"Année",es:"Año",de:"Jahr",pt:"Ano",nl:"Jaar",ru:"Год",zh:"年份",ja:"年",ko:"년도",ar:"السنة",hi:"वर्ष",tr:"Yıl",pl:"Rok",sv:"År",da:"År",no:"År",fi:"Vuosi",el:"Έτος",he:"שנה",th:"ปี",vi:"Năm",sw:"Mwaka"},
  sort_downloads:         {en:"Most Downloaded",it:"Più Scaricati",fr:"Plus Téléchargés",es:"Más Descargados",de:"Meist Heruntergeladen",pt:"Mais Baixados",nl:"Meest Gedownload",ru:"Чаще Скачиваемые",zh:"最多下载",ja:"ダウンロード最多",ko:"다운로드 순",ar:"الأكثر تحميلاً",hi:"सबसे अधिक डाउनलोड",tr:"En Çok İndirilen",pl:"Najczęściej Pobierane",sv:"Mest Nedladdade",da:"Mest Downloadede",no:"Mest Nedlastede",fi:"Ladatuimmat",el:"Περισσότερες Λήψεις",he:"הכי הורדו",th:"ดาวน์โหลดมากที่สุด",vi:"Tải nhiều nhất",sw:"Zilizopakuliwa Zaidi"},
  sort_newest:            {en:"Newest",it:"Più Recenti",fr:"Plus Récents",es:"Más Recientes",de:"Neueste",pt:"Mais Recentes",nl:"Nieuwste",ru:"Новые",zh:"最新",ja:"最新",ko:"최신",ar:"الأحدث",hi:"नवीनतम",tr:"En Yeni",pl:"Najnowsze",sv:"Nyaste",da:"Nyeste",no:"Nyeste",fi:"Uusimmat",el:"Νεότερα",he:"החדש ביותר",th:"ล่าสุด",vi:"Mới nhất",sw:"Mpya Zaidi"},

  // Book Details
  book_by:                {en:"by",it:"di",fr:"par",es:"por",de:"von",pt:"por",nl:"door",ru:"от",zh:"作者",ja:"著者",ko:"저자",ar:"بواسطة",hi:"द्वारा",tr:"yazar",pl:"przez",sv:"av",da:"af",no:"av",fi:"kirjoittanut",el:"από",he:"מאת",th:"โดย",vi:"bởi",sw:"na"},
  book_read:              {en:"📖 Read",it:"📖 Leggi",fr:"📖 Lire",es:"📖 Leer",de:"📖 Lesen",pt:"📖 Ler",nl:"📖 Lezen",ru:"📖 Читать",zh:"📖 阅读",ja:"📖 読む",ko:"📖 읽기",ar:"📖 اقرأ",hi:"📖 पढ़ें",tr:"📖 Oku",pl:"📖 Czytaj",sv:"📖 Läs",da:"📖 Læs",no:"📖 Les",fi:"📖 Lue",el:"📖 Διάβασε",he:"📖 קרא",th:"📖 อ่าน",vi:"📖 Đọc",sw:"📖 Soma"},
  book_download:          {en:"⬇️ Download",it:"⬇️ Scarica",fr:"⬇️ Télécharger",es:"⬇️ Descargar",de:"⬇️ Herunterladen",pt:"⬇️ Baixar",nl:"⬇️ Downloaden",ru:"⬇️ Скачать",zh:"⬇️ 下载",ja:"⬇️ ダウンロード",ko:"⬇️ 다운로드",ar:"⬇️ تحميل",hi:"⬇️ डाउनलोड",tr:"⬇️ İndir",pl:"⬇️ Pobierz",sv:"⬇️ Ladda ner",da:"⬇️ Download",no:"⬇️ Last ned",fi:"⬇️ Lataa",el:"⬇️ Λήψη",he:"⬇️ הורד",th:"⬇️ ดาวน์โหลด",vi:"⬇️ Tải xuống",sw:"⬇️ Pakua"},
  book_close:             {en:"✕ Close",it:"✕ Chiudi",fr:"✕ Fermer",es:"✕ Cerrar",de:"✕ Schließen",pt:"✕ Fechar",nl:"✕ Sluiten",ru:"✕ Закрыть",zh:"✕ 关闭",ja:"✕ 閉じる",ko:"✕ 닫기",ar:"✕ إغلاق",hi:"✕ बंद करें",tr:"✕ Kapat",pl:"✕ Zamknij",sv:"✕ Stäng",da:"✕ Luk",no:"✕ Lukk",fi:"✕ Sulje",el:"✕ Κλείσιμο",he:"✕ סגור",th:"✕ ปิด",vi:"✕ Đóng",sw:"✕ Funga"},
  book_no_desc:           {en:"No description available.",it:"Nessuna descrizione disponibile.",fr:"Aucune description disponible.",es:"No hay descripción disponible.",de:"Keine Beschreibung verfügbar.",pt:"Nenhuma descrição disponível.",nl:"Geen beschrijving beschikbaar.",ru:"Описание недоступно.",zh:"暂无描述。",ja:"説明はありません。",ko:"설명이 없습니다.",ar:"لا يوجد وصف متاح.",hi:"कोई विवरण उपलब्ध नहीं है।",tr:"Açıklama mevcut değil.",pl:"Brak opisu.",sv:"Ingen beskrivning tillgänglig.",da:"Ingen beskrivelse tilgængelig.",no:"Ingen beskrivelse tilgjengelig.",fi:"Kuvausta ei saatavilla.",el:"Δεν υπάρχει διαθέσιμη περιγραφή.",he:"אין תיאור זמין.",th:"ไม่มีคำอธิบาย",vi:"Không có mô tả.",sw:"Hakuna maelezo yanayopatikana."},
  book_pages:             {en:"{n} pages",it:"{n} pagine",fr:"{n} pages",es:"{n} páginas",de:"{n} Seiten",pt:"{n} páginas",nl:"{n} pagina's",ru:"{n} стр.",zh:"{n} 页",ja:"{n} ページ",ko:"{n}쪽",ar:"{n} صفحة",hi:"{n} पृष्ठ",tr:"{n} sayfa",pl:"{n} stron",sv:"{n} sidor",da:"{n} sider",no:"{n} sider",fi:"{n} sivua",el:"{n} σελίδες",he:"{n} עמודים",th:"{n} หน้า",vi:"{n} trang",sw:"{n} kurasa"},
  book_year:              {en:"📅 {year}",it:"📅 {year}",fr:"📅 {year}",es:"📅 {year}",de:"📅 {year}",pt:"📅 {year}",nl:"📅 {year}",ru:"📅 {year} г.",zh:"📅 {year}年",ja:"📅 {year}年",ko:"📅 {year}년",ar:"📅 {year}",hi:"📅 {year}",tr:"📅 {year}",pl:"📅 {year} r.",sv:"📅 {year}",da:"📅 {year}",no:"📅 {year}",fi:"📅 {year}",el:"📅 {year}",he:"📅 {year}",th:"📅 {year}",vi:"📅 {year}",sw:"📅 {year}"},
  book_isbn:              {en:"ISBN: {isbn}",it:"ISBN: {isbn}",fr:"ISBN: {isbn}",es:"ISBN: {isbn}",de:"ISBN: {isbn}",pt:"ISBN: {isbn}",nl:"ISBN: {isbn}",ru:"ISBN: {isbn}",zh:"ISBN: {isbn}",ja:"ISBN: {isbn}",ko:"ISBN: {isbn}",ar:"ISBN: {isbn}",hi:"ISBN: {isbn}",tr:"ISBN: {isbn}",pl:"ISBN: {isbn}",sv:"ISBN: {isbn}",da:"ISBN: {isbn}",no:"ISBN: {isbn}",fi:"ISBN: {isbn}",el:"ISBN: {isbn}",he:"ISBN: {isbn}",th:"ISBN: {isbn}",vi:"ISBN: {isbn}",sw:"ISBN: {isbn}"},
  book_publisher:         {en:"📘 {publisher}",it:"📘 {publisher}",fr:"📘 {publisher}",es:"📘 {publisher}",de:"📘 {publisher}",pt:"📘 {publisher}",nl:"📘 {publisher}",ru:"📘 {publisher}",zh:"📘 {publisher}",ja:"📘 {publisher}",ko:"📘 {publisher}",ar:"📘 {publisher}",hi:"📘 {publisher}",tr:"📘 {publisher}",pl:"📘 {publisher}",sv:"📘 {publisher}",da:"📘 {publisher}",no:"📘 {publisher}",fi:"📘 {publisher}",el:"📘 {publisher}",he:"📘 {publisher}",th:"📘 {publisher}",vi:"📘 {publisher}",sw:"📘 {publisher}"},
  book_downloads:         {en:"⬇️ {n}",it:"⬇️ {n}",fr:"⬇️ {n}",es:"⬇️ {n}",de:"⬇️ {n}",pt:"⬇️ {n}",nl:"⬇️ {n}",ru:"⬇️ {n}",zh:"⬇️ {n}",ja:"⬇️ {n}",ko:"⬇️ {n}",ar:"⬇️ {n}",hi:"⬇️ {n}",tr:"⬇️ {n}",pl:"⬇️ {n}",sv:"⬇️ {n}",da:"⬇️ {n}",no:"⬇️ {n}",fi:"⬇️ {n}",el:"⬇️ {n}",he:"⬇️ {n}",th:"⬇️ {n}",vi:"⬇️ {n}",sw:"⬇️ {n}"},
  book_language:          {en:"Language: {lang}",it:"Lingua: {lang}",fr:"Langue: {lang}",es:"Idioma: {lang}",de:"Sprache: {lang}",pt:"Idioma: {lang}",nl:"Taal: {lang}",ru:"Язык: {lang}",zh:"语言: {lang}",ja:"言語: {lang}",ko:"언어: {lang}",ar:"اللغة: {lang}",hi:"भाषा: {lang}",tr:"Dil: {lang}",pl:"Język: {lang}",sv:"Språk: {lang}",da:"Sprog: {lang}",no:"Språk: {lang}",fi:"Kieli: {lang}",el:"Γλώσσα: {lang}",he:"שפה: {lang}",th:"ภาษา: {lang}",vi:"Ngôn ngữ: {lang}",sw:"Lugha: {lang}"},
  book_category:          {en:"📂 {cat}",it:"📂 {cat}",fr:"📂 {cat}",es:"📂 {cat}",de:"📂 {cat}",pt:"📂 {cat}",nl:"📂 {cat}",ru:"📂 {cat}",zh:"📂 {cat}",ja:"📂 {cat}",ko:"📂 {cat}",ar:"📂 {cat}",hi:"📂 {cat}",tr:"📂 {cat}",pl:"📂 {cat}",sv:"📂 {cat}",da:"📂 {cat}",no:"📂 {cat}",fi:"📂 {cat}",el:"📂 {cat}",he:"📂 {cat}",th:"📂 {cat}",vi:"📂 {cat}",sw:"📂 {cat}"},

  // Auth
  auth_login_title:       {en:"🔐 Login",it:"🔐 Accedi",fr:"🔐 Connexion",es:"🔐 Iniciar sesión",de:"🔐 Anmelden",pt:"🔐 Entrar",nl:"🔐 Inloggen",ru:"🔐 Вход",zh:"🔐 登录",ja:"🔐 ログイン",ko:"🔐 로그인",ar:"🔐 تسجيل الدخول",hi:"🔐 लॉग इन",tr:"🔐 Giriş Yap",pl:"🔐 Zaloguj się",sv:"🔐 Logga in",da:"🔐 Log ind",no:"🔐 Logg inn",fi:"🔐 Kirjaudu",el:"🔐 Σύνδεση",he:"🔐 התחברות",th:"🔐 เข้าสู่ระบบ",vi:"🔐 Đăng nhập",sw:"🔐 Ingia"},
  auth_register_title:    {en:"📝 Register",it:"📝 Registrati",fr:"📝 Inscription",es:"📝 Registrarse",de:"📝 Registrieren",pt:"📝 Registrar",nl:"📝 Registreren",ru:"📝 Регистрация",zh:"📝 注册",ja:"📝 登録",ko:"📝 회원가입",ar:"📝 التسجيل",hi:"📝 पंजीकरण",tr:"📝 Kayıt Ol",pl:"📝 Rejestracja",sv:"📝 Registrera",da:"📝 Registrer",no:"📝 Registrer",fi:"📝 Rekisteröidy",el:"📝 Εγγραφή",he:"📝 הרשמה",th:"📝 สมัครสมาชิก",vi:"📝 Đăng ký",sw:"📝 Jisajili"},
  auth_username:          {en:"Username",it:"Nome utente",fr:"Nom d'utilisateur",es:"Nombre de usuario",de:"Benutzername",pt:"Nome de usuário",nl:"Gebruikersnaam",ru:"Имя пользователя",zh:"用户名",ja:"ユーザー名",ko:"사용자명",ar:"اسم المستخدم",hi:"उपयोगकर्ता नाम",tr:"Kullanıcı adı",pl:"Nazwa użytkownika",sv:"Användarnamn",da:"Brugernavn",no:"Brukernavn",fi:"Käyttäjätunnus",el:"Όνομα χρήστη",he:"שם משתמש",th:"ชื่อผู้ใช้",vi:"Tên đăng nhập",sw:"Jina la mtumiaji"},
  auth_email:             {en:"Email",it:"Email",fr:"Email",es:"Correo electrónico",de:"E-Mail",pt:"Email",nl:"E-mail",ru:"Эл. почта",zh:"邮箱",ja:"メール",ko:"이메일",ar:"البريد الإلكتروني",hi:"ईमेल",tr:"E-posta",pl:"Email",sv:"E-post",da:"E-mail",no:"E-post",fi:"Sähköposti",el:"Email",he:"דוא\"ל",th:"อีเมล",vi:"Email",sw:"Barua pepe"},
  auth_password:          {en:"Password",it:"Password",fr:"Mot de passe",es:"Contraseña",de:"Passwort",pt:"Senha",nl:"Wachtwoord",ru:"Пароль",zh:"密码",ja:"パスワード",ko:"비밀번호",ar:"كلمة المرور",hi:"पासवर्ड",tr:"Şifre",pl:"Hasło",sv:"Lösenord",da:"Adgangskode",no:"Passord",fi:"Salasana",el:"Κωδικός",he:"סיסמה",th:"รหัสผ่าน",vi:"Mật khẩu",sw:"Nenosiri"},
  auth_confirm:           {en:"Confirm Password",it:"Conferma Password",fr:"Confirmer le mot de passe",es:"Confirmar Contraseña",de:"Passwort bestätigen",pt:"Confirmar Senha",nl:"Bevestig Wachtwoord",ru:"Подтвердите пароль",zh:"确认密码",ja:"パスワード確認",ko:"비밀번호 확인",ar:"تأكيد كلمة المرور",hi:"पासवर्ड की पुष्टि करें",tr:"Şifreyi Onayla",pl:"Potwierdź hasło",sv:"Bekräfta lösenord",da:"Bekræft adgangskode",no:"Bekreft passord",fi:"Vahvista salasana",el:"Επιβεβαίωση κωδικού",he:"אימות סיסמה",th:"ยืนยันรหัสผ่าน",vi:"Xác nhận mật khẩu",sw:"Thibitisha Nenosiri"},
  auth_register_btn:      {en:"📝 Create Account",it:"📝 Crea Account",fr:"📝 Créer un compte",es:"📝 Crear cuenta",de:"📝 Konto erstellen",pt:"📝 Criar conta",nl:"📝 Account aanmaken",ru:"📝 Создать аккаунт",zh:"📝 创建账户",ja:"📝 アカウント作成",ko:"📝 계정 만들기",ar:"📝 إنشاء حساب",hi:"📝 खाता बनाएं",tr:"📝 Hesap Oluştur",pl:"📝 Utwórz konto",sv:"📝 Skapa konto",da:"📝 Opret konto",no:"📝 Opprett konto",fi:"📝 Luo tili",el:"📝 Δημιουργία λογαριασμού",he:"📝 צור חשבון",th:"📝 สร้างบัญชี",vi:"📝 Tạo tài khoản",sw:"📝 Unda Akaunti"},
  auth_login_btn:         {en:"🔐 Sign In",it:"🔐 Accedi",fr:"🔐 Se connecter",es:"🔐 Iniciar sesión",de:"🔐 Anmelden",pt:"🔐 Entrar",nl:"🔐 Inloggen",ru:"🔐 Войти",zh:"🔐 登录",ja:"🔐 ログイン",ko:"🔐 로그인",ar:"🔐 تسجيل الدخول",hi:"🔐 लॉग इन करें",tr:"🔐 Giriş Yap",pl:"🔐 Zaloguj się",sv:"🔐 Logga in",da:"🔐 Log ind",no:"🔐 Logg inn",fi:"🔐 Kirjaudu",el:"🔐 Σύνδεση",he:"🔐 התחבר",th:"🔐 เข้าสู่ระบบ",vi:"🔐 Đăng nhập",sw:"🔐 Ingia"},
  auth_no_account:        {en:"Don't have an account? {link}",it:"Non hai un account? {link}",fr:"Pas de compte? {link}",es:"¿Sin cuenta? {link}",de:"Noch kein Konto? {link}",pt:"Não tem conta? {link}",nl:"Geen account? {link}",ru:"Нет аккаунта? {link}",zh:"没有账户？{link}",ja:"アカウントがありませんか？{link}",ko:"계정이 없으신가요? {link}",ar:"ليس لديك حساب؟ {link}",hi:"खाता नहीं है? {link}",tr:"Hesabınız yok mu? {link}",pl:"Nie masz konta? {link}",sv:"Inget konto? {link}",da:"Ingen konto? {link}",no:"Ingen konto? {link}",fi:"Eikö sinulla ole tiliä? {link}",el:"Δεν έχετε λογαριασμό; {link}",he:"אין לך חשבון? {link}",th:"ยังไม่มีบัญชี? {link}",vi:"Chưa có tài khoản? {link}",sw:"Huna akaunti? {link}"},
  auth_has_account:       {en:"Already have an account? {link}",it:"Hai già un account? {link}",fr:"Déjà un compte? {link}",es:"¿Ya tienes cuenta? {link}",de:"Bereits ein Konto? {link}",pt:"Já tem conta? {link}",nl:"Al een account? {link}",ru:"Уже есть аккаунт? {link}",zh:"已有账户？{link}",ja:"すでにアカウントをお持ちですか？{link}",ko:"이미 계정이 있으신가요? {link}",ar:"هل لديك حساب؟ {link}",hi:"पहले से खाता है? {link}",tr:"Zaten hesabınız var mı? {link}",pl:"Masz już konto? {link}",sv:"Har du redan ett konto? {link}",da:"Har du allerede en konto? {link}",no:"Har du allerede en konto? {link}",fi:"Onko sinulla jo tili? {link}",el:"Έχετε ήδη λογαριασμό; {link}",he:"כבר יש לך חשבון? {link}",th:"มีบัญชีอยู่แล้ว? {link}",vi:"Đã có tài khoản? {link}",sw:"Tayari una akaunti? {link}"},
  auth_login_link:        {en:"Log in",it:"Accedi",fr:"Connectez-vous",es:"Inicia sesión",de:"Anmelden",pt:"Entre",nl:"Log in",ru:"Войдите",zh:"登录",ja:"ログイン",ko:"로그인",ar:"تسجيل الدخول",hi:"लॉग इन करें",tr:"Giriş yap",pl:"Zaloguj się",sv:"Logga in",da:"Log ind",no:"Logg inn",fi:"Kirjaudu",el:"Συνδεθείτε",he:"התחבר",th:"เข้าสู่ระบบ",vi:"Đăng nhập",sw:"Ingia"},
  auth_register_link:     {en:"Register",it:"Registrati",fr:"Inscrivez-vous",es:"Regístrate",de:"Registrieren",pt:"Registre-se",nl:"Registreer",ru:"Зарегистрируйтесь",zh:"注册",ja:"登録",ko:"회원가입",ar:"سجل",hi:"पंजीकरण करें",tr:"Kayıt ol",pl:"Zarejestruj się",sv:"Registrera",da:"Registrer",no:"Registrer",fi:"Rekisteröidy",el:"Εγγραφείτε",he:"הירשם",th:"สมัครสมาชิก",vi:"Đăng ký",sw:"Jisajili"},
  auth_required:          {en:"All fields are required",it:"Tutti i campi sono obbligatori",fr:"Tous les champs sont requis",es:"Todos los campos son obligatorios",de:"Alle Felder sind erforderlich",pt:"Todos os campos são obrigatórios",nl:"Alle velden zijn verplicht",ru:"Все поля обязательны",zh:"所有字段都是必填的",ja:"すべてのフィールドは必須です",ko:"모든 필드는 필수입니다",ar:"جميع الحقول مطلوبة",hi:"सभी फ़ील्ड आवश्यक हैं",tr:"Tüm alanlar zorunludur",pl:"Wszystkie pola są wymagane",sv:"Alla fält är obligatoriska",da:"Alle felter er påkrævet",no:"Alle felt er påkrevd",fi:"Kaikki kentät ovat pakollisia",el:"Όλα τα πεδία είναι υποχρεωτικά",he:"כל השדות נדרשים",th:"ทุกฟิลด์จำเป็น",vi:"Tất cả các trường đều bắt buộc",sw:"Sehemu zote zinahitajika"},
  auth_pass_mismatch:     {en:"Passwords do not match",it:"Le password non corrispondono",fr:"Les mots de passe ne correspondent pas",es:"Las contraseñas no coinciden",de:"Passwörter stimmen nicht überein",pt:"As senhas não coincidem",nl:"Wachtwoorden komen niet overeen",ru:"Пароли не совпадают",zh:"密码不匹配",ja:"パスワードが一致しません",ko:"비밀번호가 일치하지 않습니다",ar:"كلمات المرور غير متطابقة",hi:"पासवर्ड मेल नहीं खाते",tr:"Şifreler eşleşmiyor",pl:"Hasła nie są zgodne",sv:"Lösenorden matchar inte",da:"Adgangskoderne matcher ikke",no:"Passordene samsvarer ikke",fi:"Salasanat eivät täsmää",el:"Οι κωδικοί δεν ταιριάζουν",he:"הסיסמאות אינן תואמות",th:"รหัสผ่านไม่ตรงกัน",vi:"Mật khẩu không khớp",sw:"Nyenosiri hazilingani"},
  auth_username_taken:    {en:"Username already taken",it:"Nome utente già in uso",fr:"Nom d'utilisateur déjà pris",es:"Nombre de usuario ya en uso",de:"Benutzername bereits vergeben",pt:"Nome de usuário já em uso",nl:"Gebruikersnaam al in gebruik",ru:"Имя пользователя уже занято",zh:"用户名已被使用",ja:"ユーザー名は既に使用されています",ko:"사용자명이 이미 사용 중입니다",ar:"اسم المستخدم مستخدم بالفعل",hi:"उपयोगकर्ता नाम पहले से लिया गया है",tr:"Kullanıcı adı zaten alınmış",pl:"Nazwa użytkownika jest już zajęta",sv:"Användarnamnet är redan upptaget",da:"Brugernavnet er allerede optaget",no:"Brukernavnet er allerede tatt",fi:"Käyttäjätunnus on jo käytössä",el:"Το όνομα χρήστη είναι ήδη κατειλημμένο",he:"שם המשתמש כבר תפוס",th:"ชื่อผู้ใช้นี้มีอยู่แล้ว",vi:"Tên đăng nhập đã được sử dụng",sw:"Jina la mtumiaji tayari linatumika"},
  auth_email_taken:       {en:"Email already registered",it:"Email già registrata",fr:"Email déjà enregistré",es:"Correo ya registrado",de:"E-Mail bereits registriert",pt:"Email já registrado",nl:"E-mail al geregistreerd",ru:"Email уже зарегистрирован",zh:"邮箱已注册",ja:"メールは既に登録されています",ko:"이메일이 이미 등록되었습니다",ar:"البريد الإلكتروني مسجل بالفعل",hi:"ईमेल पहले से पंजीकृत है",tr:"E-posta zaten kayıtlı",pl:"Email już zarejestrowany",sv:"E-post redan registrerad",da:"E-mail allerede registreret",no:"E-post allerede registrert",fi:"Sähköposti on jo rekisteröity",el:"Το email είναι ήδη εγγεγραμμένο",he:"הדוא\"ל כבר רשום",th:"อีเมลนี้ลงทะเบียนแล้ว",vi:"Email đã được đăng ký",sw:"Barua pepe tayari imesajiliwa"},
  auth_invalid:           {en:"Invalid username or password",it:"Nome utente o password non validi",fr:"Nom d'utilisateur ou mot de passe invalide",es:"Usuario o contraseña inválidos",de:"Ungültiger Benutzername oder Passwort",pt:"Usuário ou senha inválidos",nl:"Ongeldige gebruikersnaam of wachtwoord",ru:"Неверное имя пользователя или пароль",zh:"用户名或密码无效",ja:"ユーザー名またはパスワードが無効です",ko:"사용자명 또는 비밀번호가 잘못되었습니다",ar:"اسم المستخدم أو كلمة المرور غير صالحة",hi:"अमान्य उपयोगकर्ता नाम या पासवर्ड",tr:"Geçersiz kullanıcı adı veya şifre",pl:"Nieprawidłowa nazwa użytkownika lub hasło",sv:"Ogiltigt användarnamn eller lösenord",da:"Ugyldigt brugernavn eller adgangskode",no:"Ugyldig brukernavn eller passord",fi:"Virheellinen käyttäjätunnus tai salasana",el:"Μη έγκυρο όνομα χρήστη ή κωδικός",he:"שם משתמש או סיסמה לא חוקיים",th:"ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",vi:"Tên đăng nhập hoặc mật khẩu không hợp lệ",sw:"Jina la mtumiaji au nenosiri si sahihi"},

  // Upload
  upload_title:           {en:"📤 Upload Book",it:"📤 Carica Libro",fr:"📤 Télécharger",es:"📤 Subir libro",de:"📤 Hochladen",pt:"📤 Enviar",nl:"📤 Uploaden",ru:"📤 Загрузить",zh:"📤 上传",ja:"📤 アップロード",ko:"📤 업로드",ar:"📤 تحميل",hi:"📤 अपलोड",tr:"📤 Yükle",pl:"📤 Prześlij",sv:"📤 Ladda upp",da:"📤 Upload",no:"📤 Last opp",fi:"📤 Lähetä",el:"📤 Μεταφόρτωση",he:"📤 העלה",th:"📤 อัปโหลด",vi:"📤 Tải lên",sw:"📤 Pakia"},
  upload_dropzone:        {en:"Drag & drop your book here, or click to browse",it:"Trascina il libro qui o clicca per sfogliare",fr:"Glissez-déposez votre livre ici",es:"Arrastra y suelta tu libro aquí",de:"Ziehen Sie Ihr Buch hierher",pt:"Arraste e solte seu livro aqui",nl:"Sleep je boek hierheen",ru:"Перетащите книгу сюда",zh:"将书籍拖放到此处",ja:"本をここにドラッグ＆ドロップ",ko:"책을 여기로 끌어다 놓으세요",ar:"اسحب وأفلت كتابك هنا",hi:"अपनी पुस्तक यहाँ खींचें",tr:"Kitabınızı buraya sürükleyin",pl:"Przeciągnij książkę tutaj",sv:"Dra och släpp din bok här",da:"Træk og slip din bog her",no:"Dra og slipp boken din her",fi:"Vedä ja pudota kirjasi tähän",el:"Σύρετε το βιβλίο σας εδώ",he:"גרור ושחרר את הספר שלך כאן",th:"ลากและวางหนังสือของคุณที่นี่",vi:"Kéo thả sách của bạn vào đây",sw:"Buruta na uache kitabu chako hapa"},
  upload_max_size:        {en:"Max: 50 MB",it:"Max: 50 MB",fr:"Max: 50 Mo",es:"Máx: 50 MB",de:"Max: 50 MB",pt:"Máx: 50 MB",nl:"Max: 50 MB",ru:"Макс: 50 МБ",zh:"最大: 50 MB",ja:"最大: 50MB",ko:"최대: 50MB",ar:"الأقصى: 50 ميجابايت",hi:"अधिकतम: 50 MB",tr:"Maks: 50 MB",pl:"Maks: 50 MB",sv:"Max: 50 MB",da:"Maks: 50 MB",no:"Maks: 50 MB",fi:"Maks: 50 Mt",el:"Μέγ: 50 MB",he:"מקס: 50 MB",th:"สูงสุด: 50 MB",vi:"Tối đa: 50 MB",sw":"Kiwango: 50 MB"},
  upload_success:         {en:"✅ Book uploaded!",it:"✅ Libro caricato!",fr:"✅ Livre téléchargé!",es:"✅ ¡Libro subido!",de:"✅ Buch hochgeladen!",pt:"✅ Livro enviado!",nl:"✅ Boek geüpload!",ru:"✅ Книга загружена!",zh:"✅ 上传成功!",ja:"✅ アップロード完了!",ko:"✅ 업로드 완료!",ar:"✅ تم التحميل!",hi:"✅ अपलोड सफल!",tr:"✅ Yüklendi!",pl:"✅ Przesłano!",sv:"✅ Uppladdad!",da:"✅ Uploadet!",no:"✅ Lastet opp!",fi:"✅ Lähetetty!",el:"✅ Μεταφορτώθηκε!",he:"✅ הועלה!",th:"✅ อัปโหลดสำเร็จ!",vi:"✅ Đã tải lên!",sw:"✅ Imepakiwa!"},

  // Footer
  footer_title:           {en:"📚 Bookshelf Library",it:"📚 Bookshelf Library",fr:"📚 Bookshelf Library",es:"📚 Bookshelf Library",de:"📚 Bookshelf Library",pt:"📚 Bookshelf Library",nl:"📚 Bookshelf Library",ru:"📚 Bookshelf Library",zh:"📚 Bookshelf Library",ja:"📚 Bookshelf Library",ko:"📚 Bookshelf Library",ar:"📚 مكتبة الكتب",hi:"📚 बुकशेल्फ़ लाइब्रेरी",tr:"📚 Kitaplık Kütüphanesi",pl:"📚 Biblioteczka",sv:"📚 Bokhylla Bibliotek",da:"📚 Bogreol Bibliotek",no:"📚 Bokhylle Bibliotek",fi:"📚 Kirjahylly Kirjasto",el:"📚 Βιβλιοθήκη",he:"📚 ספריית המדף",th:"📚 ห้องสมุดชั้นหนังสือ",vi:"📚 Thư viện Tủ sách",sw:"📚 Maktaba ya Rafu"},
  footer_disclaimer:      {en:"📚 This is a non-profit platform dedicated to spreading knowledge and intelligence. All books are shared for educational purposes only. If you are a copyright holder and believe any content infringes your rights, please contact us for immediate removal.",it:"📚 Questa è una piattaforma senza scopo di lucro dedicata alla diffusione della conoscenza. Tutti i libri sono condivisi solo a scopo educativo. Se sei un detentore di copyright, contattaci per la rimozione immediata.",fr:"📚 Plateforme à but non lucratif dédiée au savoir. Livres partagés à des fins éducatives.",es:"📚 Plataforma sin fines de lucro para el conocimiento. Libros con fines educativos.",de:"📚 Gemeinnützige Plattform zur Wissensvermittlung. Bücher zu Bildungszwecken.",pt:"📚 Plataforma sem fins lucrativos para conhecimento. Livros para fins educacionais.",nl:"📚 Non-profit platform voor kennis. Boeken voor educatieve doeleinden.",ru:"📚 Некоммерческая платформа для знаний. Книги в образовательных целях.",zh:"📚 非盈利知识平台。书籍仅供教育用途。",ja:"📚 非営利知識プラットフォーム。教育目的の書籍。",ko:"📚 비영리 지식 플랫폼. 교육 목적의 도서.",ar:"📚 منصة غير ربحية للمعرفة. الكتب للأغراض التعليمية.",hi:"📚 ज्ञान के लिए गैर-लाभकारी मंच। शैक्षिक उद्देश्यों के लिए पुस्तकें।",tr:"📚 Bilgi için kar amacı gütmeyen platform. Eğitim amaçlı kitaplar.",pl:"📚 Non-profitowa platforma wiedzy. Książki w celach edukacyjnych.",sv:"📚 Icke-vinstdrivande plattform för kunskap. Böcker i utbildningssyfte.",da:"📚 Non-profit platform for viden. Bøger til undervisningsformål.",no:"📚 Non-profit plattform for kunnskap. Bøker til utdanningsformål.",fi:"📚 Voittoa tavoittelematon tietoalusta. Kirjoja koulutustarkoituksiin.",el:"📚 Μη κερδοσκοπική πλατφόρμα γνώσης. Βιβλία για εκπαιδευτικούς σκοπούς.",he:"📚 פלטפורמה ללא מטרת רווח להפצת ידע. ספרים למטרות חינוכיות.",th:"📚 แพลตฟอร์มที่ไม่แสวงหากำไรเพื่อความรู้ หนังสือเพื่อการศึกษา",vi:"📚 Nền tảng phi lợi nhuận vì tri thức. Sách vì mục đích giáo dục.",sw:"📚 Jukwaa la kutolipa kwa ajili ya kusambaza maarifa. Vitabu kwa madhumuni ya kielimu."},
  footer_credit:          {en:"Made with ❤️ by",it:"Fatto con ❤️ da",fr:"Fait avec ❤️ par",es:"Hecho con ❤️ por",de:"Gemacht mit ❤️ von",pt:"Feito com ❤️ por",nl:"Gemaakt met ❤️ door",ru:"Сделано с ❤️",zh:"用 ❤️ 制作",ja:"❤️ を作りました",ko:"❤️ 로 만들었습니다",ar:"صنع بـ ❤️ من",hi:"❤️ से बनाया गया",tr:"❤️ ile yapıldı",pl:"Zrobione z ❤️ przez",sv:"Gjord med ❤️ av",da:"Lavet med ❤️ af",no:"Laget med ❤️ av",fi:"Tehty ❤️:llä",el:"Φτιαγμένο με ❤️ από",he:"נעשה ב- ❤️ על ידי",th:"ทำด้วย ❤️ โดย",vi:"Thực hiện với ❤️ bởi",sw:"Imetengenezwa kwa ❤️ na"},
  footer_sky:             {en:"Skyy",it:"Skyy",fr:"Skyy",es:"Skyy",de:"Skyy",pt:"Skyy",nl:"Skyy",ru:"Skyy",zh:"Skyy",ja:"Skyy",ko:"Skyy",ar:"سكاي",hi:"स्काई",tr:"Skyy",pl:"Skyy",sv:"Skyy",da:"Skyy",no:"Skyy",fi:"Skyy",el:"Skyy",he:"סקיי",th:"สกาย",vi:"Skyy",sw:"Skyy"},
};

function t(key, lang, params = {}) {
  const entry = T[key];
  if (!entry) return `{${key}}`;
  const str = entry[lang] || entry[DEFAULT_LANG] || `{${key}}`;
  return str.replace(/\{(\w+)\}/g, (_, k) => params[k] !== undefined ? params[k] : `{${k}}`);
}

function translate(key, lang, params = {}) {
  return t(key, lang, params);
}

function getLanguages() {
  return SUPPORTED_LANGUAGES;
}

function getDefaultLang() {
  return DEFAULT_LANG;
}

module.exports = { translate, t, getLanguages, getDefaultLang, SUPPORTED_LANGUAGES };